apiVersion: v1
kind: Service
metadata:
  labels:
    app: work-queue
    component:  work-queue
    chapter:  jobs
  name: work-queue
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: work-queue
    component: queue